apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-name
spec:
  template:
    spec:
      containers:
        - image: app
          securityContext:
            seccompProfile:
              type: Unconfined
            capabilities:
              add:
                - SYS_PTRACE
          stdin: true
          tty: true
      restartPolicy: Never
