apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-name
spec:
  template:
    metadata:
      name: podName
    spec:
      containers:
        - name: container-name
          image: project-folder
          env:
            - name: DOPPLER_TOKEN
              value: $(DOPPLER_TOKEN)
